# Generated by Django 5.0.6 on 2024-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
