# Generated by Django 5.0.6 on 2024-07-12 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='first_name',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
