# Generated by Django 5.0.6 on 2024-07-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0002_teacher_bio_alter_teacher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='first_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
