# Generated by Django 5.0.6 on 2024-07-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_first_name'),
        ('student', '0002_student_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student.student'),
        ),
    ]
