# Generated by Django 5.0.6 on 2024-07-14 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_name'),
        ('student', '0002_student_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.ForeignKey(default='default_first_name', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student.student'),
        ),
    ]
