# Generated by Django 5.0.6 on 2024-07-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0002_rename_period_name_classperiod_period_title'),
        ('classroom', '0002_classroom_delete_classs'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='period_title',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='period_name', to='classperiod.classperiod'),
        ),
    ]
