# Generated by Django 5.0.6 on 2024-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_first_name'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_title',
            field=models.ManyToManyField(related_name='students', to='course.course'),
        ),
    ]
