# Generated by Django 5.0.6 on 2024-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_duration', models.TimeField()),
                ('class_ta', models.CharField(max_length=20)),
                ('class_rep', models.CharField(max_length=20)),
                ('class_empty_slots', models.SmallIntegerField()),
                ('chair_numbers', models.PositiveSmallIntegerField()),
                ('tables_numbers', models.PositiveSmallIntegerField()),
                ('tv_numbers', models.PositiveSmallIntegerField()),
                ('class_code', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
